name: lets_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.10
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  lottie: ^3.0.0
  progress_dialog_null_safe: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
